### ISSUE TITLE
How to reinstantiate/refetch current indexes?

### ISSUE THREAD

**Issue by ViktorSoroka** [algolia/instantsearch.js#2318] opened 2017-09-07 17:16 UTC
I have instantiated `<InstantSearch />` component and it worked fine. The thing I want is to change one of the search result item in way that it will not match the search index anymore and reflect that in UI. How to refetch/reistantiate currently specified query? For now I should do a full page reload to get things I want.

**Comment by Haroenv** [comment] 2017-09-07 17:21
This is not possible yet, but closing as it's a duplicate

duplicate of https://github.com/algolia/react-instantsearch/issues/252

**Comment by Haroenv** [comment] 2017-09-07 17:22
Your input there is definitely more than welcome ❤️

**Closed by Haroenv** 2017-09-07 17:21 UTC

**Comment by ViktorSoroka** [comment] 2017-09-07 17:24
Thank you for the quick response.
