### ISSUE TITLE
aroundRadius and aroundLatLngViaIP handled as string in urlSync

### ISSUE THREAD

**Issue by swistak35** [algolia/instantsearch.js#1059] opened 2016-06-09 11:00 UTC
Hi,
I've custom widget in which I filter results by their location like so:

```
helper.setQueryParameter('aroundLatLngViaIP', true);
helper.setQueryParameter('aroundRadius', somevalue);
```

Search is working well and I can see these values send in HTTP requests to algolia.

Is there any particular reason to not have these values in URL when `urlSync` to enabled? Or is it just a bug?

**Comment by vvo** [comment] 2016-06-09 11:50
Hi @swistak35 this is not a bug per se but a lack in our documentation on how to track them.

Here's how to do it:

```js
var search = instantsearch({
  // ... other parameters
  urlSync: {
    trackedParameters: [
      'attribute:*', 'query', 'page', 'hitsPerPage',
      'aroundLatLngViaIP', 'aroundRadius'
    ]
  }
});
```

You could add more of them if needed. Seems right?

Thanks

**Comment by swistak35** [comment] 2016-06-14 09:44
@vvo I assumed that by default everything is tracked in urlSync and that was the thing which confused me. Thanks for your help :)

**Comment by vvo** [comment] 2016-06-14 09:45
Awesome, yes indeed we only track SOME parameters by default, this will be documented soon: https://github.com/algolia/instantsearch.js/issues/1089

**Comment by gtovar333** [comment] 2017-08-15 15:18
Hey guys, I am trying to use this for insideBoundingBox and when using the generated URL Algolia throws an error

![image](https://user-images.githubusercontent.com/1839199/29322436-175e7264-81a3-11e7-8351-9159c3c0290d.png)

Any Ideas?

**Comment by Haroenv** [comment] 2017-08-15 15:41
That’s probably because the URL parses this as a string, not a number. Let’s reopen this if you have more information on how you’re calling Algolia

**Comment by gtovar333** [comment] 2017-08-15 15:44
This is how I got it going.

 search = new instantsearch({
    // ... other parameters
    urlSync: {
      trackedParameters: [
        'attribute:*', 'query', 'page', 'hitsPerPage',
        'insideBoundingBox'
      ]
    }
  });

Url: http://localhost:3001/testSite?q=&iBB%5B0%5D%5B0%5D=34.201180305461925&iBB%5B0%5D%5B1%5D=-83.73317161926728&iBB%5B0%5D%5B2%5D=33.29681049453807&iBB%5B0%5D%5B3%5D=-85.04279318073272&p=0&is_v=1

**Comment by Haroenv** [comment] 2017-11-01 14:08
This might be fixed by https://github.com/algolia/algoliasearch-helper-js/pull/554, cc @bobylito

**Comment by bobylito** [comment] 2017-11-01 14:13
I'm making a new issue for this problem @gtovar333

**Closed** 2017-11-01 14:13 UTC
Labels: Scope: core, ❤ Bug
