### ISSUE TITLE
urlSync pushes new history state on load if searchFunction is used

### ISSUE THREAD

**Issue by austin-roberts** [algolia/instantsearch.js#2557] opened 2017-11-07 16:33 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

Code is here, urlSync seems not to work with jsfiddle:
https://jsfiddle.net/9n8Lnqas/

**Bug: What is the current behavior?**
When instant search is created and the query is modified by searchFunction, urlSync pushes a new state to history on load. This behavior was implemented in v2.2.2 with a fix for #2530 

**Bug: What is the expected behavior?**
Previous to version 2.2.2, urlSync only pushes new states after user interaction with instantsearch. If new states are being created in browser history on load, this poses a problem for sites with catalog views that utilize instantsearch. In our case, thousands of pages are immediately appended with instantsearch parameters after page/instantsearch loading. We use searchFunction for various facets that are subject to change based other previous user interactions on the site.

**Bug: What browsers are impacted? Which versions?**
All browsers that support the history API when urlSync option is used.

**Bug: What is the proposed solution?**
There may be a better way to resolve issue #2530 , or maybe additional urlSync options could make this configurable.

**What is the version you are using? Always use the latest one before opening a bug issue.**
v2.2.2 Currently using 2.2.1 to get around this.

**Comment by bobylito** [comment] 2017-11-07 17:24
Thanks @austin-roberts for opening the issue.

Before 2.2.2, you had to do 2 interactions in order to update the URL. Is the problem the fact that you have now a new state in the history even if you didn't change anything yet?

**Comment by austin-roberts** [comment] 2017-11-07 17:37
@bobylito Yes, I guess I didn't realize it was 2 because maybe we always had the first interaction taking place when instantsearch loads.

"Is the problem the fact that you have now a new state in the history even if you didn't change anything yet?" - Yes, given that we are using searchFunction, our category and other catalog views can't be appending parameters each time any of those pages are viewed only.

**Comment by bobylito** [comment] 2017-11-07 18:04
> "Is the problem the fact that you have now a new state in the history even if you didn't change anything yet?" - Yes, given that we are using searchFunction, our category and other catalog views can't be appending parameters each time any of those pages are viewed only.

@austin-roberts, I'm not sure I get the issue. With the search function you add some parameters. Do you want them displayed in the URL? Or hidden?

**Comment by austin-roberts** [comment] 2017-11-07 19:16
> I'm not sure I get the issue. With the search function you add some parameters. Do you want them displayed in the URL? Or hidden?

@bobylito So in the case of the jsfiddle I included in the bug report, just by loading that code the location will be appended with this: /?q=&idx=movies&p=0&fR%5Bgenre%5D%5B0%5D=Drama
It wouldn't be possible for us to deploy v2.2.2/2.2.3 today, given that we are making use of searchFunction. We have tens of thousands of paths that would suddenly have search parameters applied to them when loading the page, before an actual user interaction occurs with the content.

I would expect that the location search parameters wouldn't be manipulated until a user makes a physical interaction with instantsearch, but I could be wrong on this expectation as of v2.2.2.

![image](https://user-images.githubusercontent.com/16822962/32512794-6e5e97ac-c3b5-11e7-820f-ea7552e24d4c.png)

**Comment by bobylito** [comment] 2017-11-08 16:56
I haven't been able to look into this issue today. It's very high on my todo ;)

**Comment by bobylito** [comment] 2017-11-09 10:37
So I finally worked on that. And the good news is that it can be fixed in newer versions too. But first I'd like to let you know we're very sorry that you had the issue in the first place and I'd like to thank you for your patience.

So what happens is that the URL mechanics detects a change and therefore update the URL. That's the expected behavior. What is less expected is that this change happens in the searchfunction itself. That's why we have an update when the pages is first loaded. However there is a fix for that. Because we don't want changes at this moment, the initial state should be the same. And there is an option on the instantsearch function: searchParameters. Here is how I fixed your example:

```diff
        var search = instantsearch({
          appId: 'latency',
          apiKey: '6be0576ff61c053d5f9a3225e2a90f76',
          indexName: 'movies',
          searchParameters: {
            facets: [
              'genre'
            ],
+            facetsRefinements: {
+             genre: ['Drama']
+            }
+          },
          searchFunction: function(helper) {
            helper.addFacetRefinement('genre', 'Drama');

            helper.search();
          },
          urlSync: true
        });
```

You can see the [result here](http://unadvised-sack.surge.sh/index-noNewURL.html) and the [original here](http://unadvised-sack.surge.sh).

I think we should close this issue, WDYT @austin-roberts ?

**Comment by austin-roberts** [comment] 2017-11-13 16:07
Hey @bobylito thx for this info. I think this will end up working for us.

Thank you for looking into this! I agree we should close this now.

**Comment by bobylito** [comment] 2017-11-13 16:09
Happy to help. Don't hesitate to open new issues :)

**Closed by bobylito** 2017-11-13 16:09 UTC
Labels: ❔ Investigate
