### ISSUE TITLE
Question on the page "connectCurrentRefinedValues"

### ISSUE THREAD

**Issue by olliex** [algolia/instantsearch.js#4232] opened 2019-12-02 11:39 UTC
Hi! I have a documentation issue on InstantSearch.js. I could not find what I was looking for on the page "[connectCurrentRefinedValues](https://community.algolia.com/instantsearch.js/v2/connectors/connectCurrentRefinedValues.html)".

Hi, I can't find a way to build a widget, which allows the user to clear all currently selected filters of one attribute. So instead of having eg:
- Brand: Brand name 1
- Brand: Brand name 2
- Capacity: 50ml
- Capacity: 100ml
- Capacity: 150ml

I'd like to render it like this:
- Brand: Brand 1, Brand 2    xClearUrl
- Capacity: 50ml, 100ml, 150ml    xClearUrl

Any help on that topic?

**Comment by Haroenv** [comment] 2019-12-02 12:30
This is the behaviour of createURL & refine in InstantSearch v3, are you stuck on v2?

**Comment by olliex** [comment] 2019-12-02 12:42
I guess so, we use Algolia as extension for Magento 2, **Algolia Search for Magento 2**

**Comment by yannickcr** [comment] 2019-12-02 15:02
For InstantSearch v2 you can group refinements based on the attribute then, since the connector does not expose any way to clear multiple refinements at one, you''l need to reproduce part of [`connectCurrentRefinedValues` internals](https://github.com/algolia/instantsearch.js/blob/12f473283c555c2c9ef5f3e3883486eddfb37448/src/connectors/current-refined-values/connectCurrentRefinedValues.js#L356-L394).

Based on the example from [connectCurrentRefinedValues](https://community.algolia.com/instantsearch.js/v2/connectors/connectCurrentRefinedValues.html#example) here's a possible implementation of this: https://codesandbox.io/s/instantsearchjs-app-i15st

**Comment by tkrugg** [comment] 2019-12-03 09:14
@olliex I'm closing this for now but feel free to reopen if you want to further discuss.

**Closed by tkrugg** 2019-12-03 09:14 UTC
