### ISSUE TITLE
algolia nbHits giving different count for different replicas

### ISSUE THREAD

**Issue by soniya90** [algolia/instantsearch.js#2286] opened 2017-08-11 12:44 UTC
sometimes nbHits gives proper count on same index and sometimes not. Count for replica indices also differs for the same query.  Please help me to find the solution.

**Comment by Haroenv** [comment] 2017-08-11 12:53
Number of hits is an approximation usually. Can you give your appID/indexName so that we can debug this? A reproducible version with your code would be helpful too, since we can then see on which level the problem occurs

**Comment by soniya90** [comment] 2017-08-14 05:10
Hello Haroenv,
Appld - WJNZFCQTYW
indexName - staging_zoodel_products_seller(default index)
ReplicaIndex - staging_zoodel_products_popular_slave (To show popularity with different ranking)

Please refer this url  http://staging.zoodel.com/en/products . Here you can see number of products(nbHits) are different sometime.  Let me know if you need more details.

Thank you for your help.

**Comment by Haroenv** [comment] 2017-08-14 07:13
Hey, seems like this is getting quite into detail and I can't replicate the differing count. I always see 33 333 results. Can you send an email to [support@algolia.com](mailto:support@algolia.com) with two queries that should have the same number of result but don't? You can look in the devtools tab, and "copy as curl" the two `queries` results that have different results, but shouldn't. 

I'll close this issue since I don't think it's related to instantsearch.js, but rather something else in the API call.

**Closed by Haroenv** 2017-08-14 07:13 UTC

**Comment by soniya90** [comment] 2017-08-14 09:28
Hey, If you check sortby : popularity/relevancy one by one, then you can see the different count. Here I am using replica index to show result for popularity having just different ranking. 
In code I am just passing indexname on change of "sortby" field.

Yes, this is using algolia API call , not instantsearch.js.

**Comment by Haroenv** [comment] 2017-08-14 10:41
Can you give detailed information on how exactly you're calling the API and send this via email, I can't replicate this on your side, but maybe a minimal example will give us more insight in what happens that causes this disparity between number of hits.
