### ISSUE TITLE
Missing last hit

### ISSUE THREAD

**Issue by SchmidtDawid** [algolia/instantsearch.js#3015] opened 2018-06-28 08:21 UTC
**Describe the bug 🐛**
Sometimes after search last page is empty. For example i got 145 hits, 24 hits per page. It is 24*6+1. On last page should be 1 hit but its 0. 

**To Reproduce 🔍**
1. search
2. go to last page
3. page is emtpy

**Expected behavior 💭**
1 hit on last page
**Screenshots 🖥**
https://imgur.com/gallery/37DERj3
Edit:
another query with this bug:
https://imgur.com/a/eylyCKz

**Environment:**
everywhere ;)

**Additional context**
We realize we have QR on this query.
https://imgur.com/a/L2dCCfG
on querys without query rules everything is fine.

**Comment by bobylito** [comment] 2018-06-28 09:02
Thanks for opening this issue.

What happens if you deactivate the query rule?

**Comment by SchmidtDawid** [comment] 2018-06-28 09:10
After remove QR we've got 6 full pages (144 hits instead 145).

**Comment by bobylito** [comment] 2018-06-29 12:28
Is the result promoted by the query rule part of the result set?

**Comment by SchmidtDawid** [comment] 2018-06-29 13:31
It seems yes. For example we have query with 144 hits and 24 hits per page. We've got 6 full pages then. If we add QR to this query then we'he got 145 hits. It makes 7 pages but last page is empty. 
I cant give you live eqample becouse we have big product rotation and it can be out of date after few minutes.

**Comment by bobylito** [comment] 2018-07-02 19:09
There is something weird. We're digging :)

**Comment by clement-leprovost** [comment] 2018-07-03 15:31
Hello @SchmidtDawid, Clément from Algolia's search engine team here... :)

There is indeed a bug. Thanks for reporting it! 👍 

FYI, it only happens on "big enough" indices (it needs incremental building to be triggered). Anyway, the cause is understood. A fix will come soon... but bear in mind that we need to deploy it on all Algolia machines before it is available. I'll update this thread when it's done.

**Comment by bobylito** [comment] 2018-07-03 19:05
Thanks @clement-leprovost for the update. Since it's not an instantsearch.js related issue I will close this ticket for now :)

**Closed by bobylito** 2018-07-03 19:05 UTC
Labels: ❔ Investigate, ❤ Bug
