### ISSUE TITLE
urlSync + Turbolinks back button not working

### ISSUE THREAD

**Issue by ThomasBush** [algolia/instantsearch.js#985] opened 2016-04-21 15:57 UTC
I am using the using instantsearch with turbolinks and am experiencing an issue where the back button is not working correctly.

My search coffeescript

```
search = instantsearch(
      appId: 'id'
      apiKey: 'key'
      indexName: 'index'
      urlSync: {
        threshold: 300
      })
```

When I search products, the url is updated as expected, search works.  If I click on a product, than click the `back` button, the url changes to the previously generated search url, but I stay on the product#show page for the instance I was viewing.  Clicking `back` button a second time takes me to the root /products page.  

This issue doesn't occur when setting `useHash: true`, unfortunately analytics team needs this to be query params.

**Comment by vvo** [comment] 2016-04-22 13:05
Can you point us to a live example of the bug you are experiencing?

Maybe build a simple reduced test case using turbolinks + instantsearch.js to demonstrate the problem?

That would help us, thanks

**Comment by ThomasBush** [comment] 2016-04-26 17:59
Sorry @vvo, it looks like you fixed with @kle-roy, but I am still experiencing the same issue, so I am trying to figure out what I am missing.  I updated my instantsearch.min.js to 1.4.5.  Does it look like I am passing the new setting correctly when instantiating?  Thanks.

```
   search = instantsearch(
      appId: 'id'
      apiKey: 'key'
      indexName: 'products'
      urlSync: {
        threshold: 300
        useHash: false
        getHistoryState: ->
          { turbolinks: true }
      }) 
```

**Comment by kle-roy** [comment] 2016-04-26 19:20
@ThomasBush : as mentioned by @vvo on #992, the `getHistoryState` feature is not released yet ; for now, you can just test it on the `develop` branch

**Comment by ThomasBush** [comment] 2016-04-26 19:25
Ah thanks, sorry, I missed that last bit.

**Comment by Spone** [comment] 2018-05-14 17:04
Hi @vvo do you have an example of how to achieve Turbolinks compatibility with the new `router` option?

**Comment by Haroenv** [comment] 2018-05-14 17:29
Seems like we need to add `{ turbolinks: true }` as the first argument of routing, cc @bobylito

**Comment by Haroenv** [comment] 2018-05-14 17:33
@Spone, can you try: 

```js
instantsearch({
  routing: {
    stateMapping: {
      stateToRoute(uiState) {
        return {
          turbolinks: true,
          ... uiState,
        };
      },
      routeToState({turbolinks, ...routeState}) {
        return routeState
      }
    }
  }
});
```

**Comment by Spone** [comment] 2018-05-15 11:14
@Haroenv it seems to work perfectly! Thanks

**Comment by Haroenv** [comment] 2018-05-15 15:54
Yes, or maybe we could make it an option to add this by default?

**Comment by bobylito** [comment] 2018-05-15 15:58
> Yes, or maybe we could make it an option to add this by default?

It's a rather specific use case and the fix is very small, I don't know if there is a strong benefit to have an option 🤔

**Comment by Spone** [comment] 2018-05-15 16:11
But `turbolinks=true` appears in the URL query string when I do that. Can I hide it?

Also, it would be great to have at least a few lines of documentation about this `turbolinks` options. It seems to be black magic :D

**Comment by bobylito** [comment] 2018-05-16 08:39
> To be clear: what breaks is that if I click on a hit, I cannot go back to the search results with one click on the back button.

Ok. Do you have an error? Maybe the problem is that the default parseURL function can't parse it back.

**Comment by bobylito** [comment] 2018-06-08 12:33
Closing this issue in favor of https://github.com/algolia/instantsearch.js/issues/2998

**Closed by bobylito** 2018-06-08 12:33 UTC
