### ISSUE TITLE
`autofocus:true` does not focus the input on first load

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#188] opened 2015-10-08 09:07 UTC
Currently, even with an empty query and `autofocus: true`, the input is not having focus on page load. Tested on Chromium Version 44.0.2403.89 Ubuntu 15.04 (64-bit)

**Comment by redox** [comment] 2015-10-09 12:29
Cannot reproduce it right now. Let's close it for now, feel free to re-open it :)

**Closed by redox** 2015-10-09 12:29 UTC
Labels: bug, ready
