### ISSUE TITLE
Instant search with infinite scroll repeats records

### ISSUE THREAD

**Issue by JanPetr** [algolia/instantsearch.js#2938] opened 2018-05-23 08:14 UTC
**Describe the bug 🐛**
Instant search page with infinite scroll enabled, repeats records/products randomly after 4-5 pages

**To Reproduce 🔍**
Go to https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=InfiniteHits.default
Click on "show more" button 4 to 5 times and observe the results loaded. You should see that some products have repeated.

**Expected behavior 💭**
Records/products should not repeat.

**Screenshots 🖥**
<img width="1095" alt="screenshot 2018-05-23 10 10 07" src="https://user-images.githubusercontent.com/1058144/40411845-e933d5e4-5e71-11e8-89fc-adbfbfb8b649.png">

**Environment:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 66.0.3359.181

**Comment by bobylito** [comment] 2018-05-23 12:08
Hi @JanPetr  I think this is a duplicate of #2928. Can you check if you have latency in your requests?

**Comment by bobylito** [comment] 2018-05-29 03:07
@JanPetr Can you try with the latest InstantSearch.js (2.7.5)?

**Comment by bobylito** [comment] 2018-06-08 14:52
@JanPetr confirmed he can't reproduce it anymore so let's close that :)

**Closed by bobylito** 2018-06-08 14:52 UTC
Labels: ❤ Bug
