### ISSUE TITLE
react instantsearch and react native - nesting connectors within a modal 

### ISSUE THREAD

**Issue by Arcade1080** [algolia/instantsearch.js#2069] opened 2017-03-22 15:35 UTC
Hi,

i'm  trying to make instantsearch run on a react native project. It is a large product list that can be filtered. Specifically i want to place the filter options in a modal dialog (https://facebook.github.io/react-native/docs/modal.html). After the modal opens, users can select various filter options and then hit 'Apply Filter', which closes the modal. 

The Problem is that  the previous alterations to the search state are gone. Any ideas on how to solve that?  

Thank you!

```js
import React, { Component } from 'react';
import { TouchableOpacity, TouchableHighlight, Image, Text, TextInput, Dimensions, Title, Icon, Header, View,  StyleSheet, Modal, ScrollView, ListView, RefreshControl } from 'react-native';


// Algolia Instantsearch
import { InstantSearch } from 'react-instantsearch/native';
import { connectSearchBox, connectInfiniteHits, connectCurrentRefinements, connectStats, connectHierarchicalMenu, connectRefinementList } from 'react-instantsearch/connectors';

// Catalog components
import SearchBox from './searchbox';
import Hits from './hits';

// Modal Content
import CurrentRefinements from './currentrefinements';
import CategoryFilter from './categoryfilter';
import SizeFilter from './sizefilter';
import PriceFilter from './pricefilter';
import ApplyFilter from './applyfilter';

// Pass Components to Algolia Connectors
const ConnectedSearchBox = connectSearchBox(SearchBox);
const ConnectedHits = connectInfiniteHits(Hits);
const ConnectedCurrentRefinements = connectCurrentRefinements(CurrentRefinements);
const ConnectedCategoryFilter = connectHierarchicalMenu(CategoryFilter);
const ConnectedSizeFilter = connectRefinementList(SizeFilter);
const ConnectedPriceFilter = connectMultiRange(PriceFilter);
const ConnectedApplyFilter=  connectStats(ApplyFilter);

class InstantSearch extends Component {

  constructor(props) {
    super(props);
  }

  render() {

      // Retrieve Redux actions and props
      const { filterModalOpen, toggleFilterModal, searchState, setSearchState, openDrawer } = this.props;
   
      return (

        <View>
            <InstantSearch
              appId="latency"
              apiKey="6be0576ff61c053d5f9a3225e2a90f76"
              indexName='ikea'
              searchState = { searchState }
              onSearchStateChange = { (st) => (  setSearchState(st) ) }
            >

              <TouchableOpacity onPress = { () => toggleFilterModal()} >
                <Text> Open Filter Modal </Text>
              </TouchableOpacity>

              <ConnectedSearchBox openDrawer = { openDrawer }/>

              <Modal
                animationType={"slide"}
                transparent={false}
                visible={filterModalOpen}
                onRequestClose={() => {alert("Modal has been closed.")}}
                > 
                <View style = {{ flex : 1 }}>
                    <ConnectedCurrentRefinements  />
                    <ConnectedCategoryFilter attributes = {['category']} />
                    <ConnectedSizeFilter attributeName = "sizes"  />
                    <ConnectedApplyFilter toggleFilterModal = {toggleFilterModal} />
                </View>
              </Modal>

              <ConnectedHits/> 

            </InstantSearch>
        </View>
        );
  }
}
```

**Comment by Haroenv** [comment] 2017-03-22 15:59
Hey, thanks for using react-instantsearch in react-native. We love to find people trying our library in less obvious platforms. However, to create an easy to reproduce 

What I notice is that you have the `InstantSearch` variable twice. Once as the class, and once imported, I think that this is already a thing that is causing errors when I try to reproduce your setup. 

I'm wondering if you can try https://sketch.expo.io/ to make an easily reproducible issue?

**Comment by Arcade1080** [comment] 2017-03-22 16:06
Thx! I´ll try https://sketch.expo.io/ an report back

**Comment by Arcade1080** [comment] 2017-03-22 16:50
sketch is not working because i cannot import the instantsearch library. However, i reduced the code and added screenshots for reference. I hope this makes sense.

```
import React, { Component } from 'react';
import { TouchableOpacity, TouchableHighlight, Image, Text, TextInput, Dimensions, Title, Icon, Header, View,  StyleSheet, Modal, ScrollView, ListView, RefreshControl } from 'react-native';


// Algolia Instantsearch
import { InstantSearch } from 'react-instantsearch/native';
import { connectSearchBox, connectInfiniteHits, connectCurrentRefinements, connectStats, connectHierarchicalMenu, connectMultiRange, connectRefinementList } from 'react-instantsearch/connectors';

// Catalog components
import Hits from './hits';

// Modal Content
import CurrentRefinements from './currentrefinements';
import CategoryFilter from './categoryfilter';
import SizeFilter from './sizefilter';
import ApplyFilter from './applyfilter';

// Pass Components to Algolia Connectors
const ConnectedHits = connectInfiniteHits(Hits);
const ConnectedCurrentRefinements = connectCurrentRefinements(CurrentRefinements);
const ConnectedCategoryFilter = connectHierarchicalMenu(CategoryFilter);
const ConnectedSizeFilter = connectRefinementList(SizeFilter);
const ConnectedApplyFilter=  connectStats(ApplyFilter);
 

// Main Component
class InstaSearch extends Component {

  constructor(props) {
    super(props);

    this.state  = {
      filterModalOpen : false,
    }
  }

  toggleFilterModal() {
      this.setState( prevState => ({
          filterModalOpen : !prevState.filterModalOpen
      }));
  }
   
  render() {

    const { filterModalOpen } = this.state;
 
    return (

      <View>
          <InstantSearch
            appId="latency"
            apiKey="6be0576ff61c053d5f9a3225e2a90f76"
            indexName='ikea'
          >

            <TestStats />

            <TouchableOpacity onPress = { this.toggleFilterModal.bind(this) } >
              <Text> Open Filter Modal </Text>
            </TouchableOpacity>

            <Modal
                animationType={"slide"}
                transparent={false}
                visible={filterModalOpen}
                > 
           
                <View style = {{ flex : 1 }}>
                    <ConnectedCurrentRefinements  />
                    <ConnectedCategoryFilter attributes = {['category']} />
                    <ConnectedSizeFilter attributeName = "sizes"  />
                    <ConnectedApplyFilter toggleFilterModal = {this.toggleFilterModal.bind(this)} />
                </View>
            </Modal>


              <ConnectedHits/> 

          </InstantSearch>
      </View>
      );
  }
}

const TestStats = connectStats( ({nbHits }) => {
  return (
    <Text> {nbHits} </Text>
  );
});

 

export default InstaSearch;
```

<img width="552" alt="1_rn_modal" src="https://cloud.githubusercontent.com/assets/4496916/24209934/cf42bc08-0f27-11e7-8851-32a2bb933f08.png">
<img width="563" alt="2_rn_modal" src="https://cloud.githubusercontent.com/assets/4496916/24209935/cf43faaa-0f27-11e7-87bc-a3093246b231.png">
<img width="549" alt="3_rn_modal" src="https://cloud.githubusercontent.com/assets/4496916/24209933/cf351e54-0f27-11e7-9af4-e7d8d8383e4e.png">
<img width="564" alt="4_rn_modal" src="https://cloud.githubusercontent.com/assets/4496916/24209932/cf338df0-0f27-11e7-98a6-9e21ed430fd0.png">
<img width="632" alt="5_rn_modal" src="https://cloud.githubusercontent.com/assets/4496916/24209936/cf6f7c5c-0f27-11e7-8bbd-3c72c886db8b.png">

**Comment by mthuret** [comment] 2017-03-28 08:48
Hi @Arcade1080 

This occurs because every time a widget is unmounted, then its removed from the search state. 
When the modal is closed, it unmounts the widgets inside, and then, their refinements are removed from the search state. 

We need to think about a new API entry that will allow users to persist a refinement even if the widget is unmounted. That way you will be able to use only [virtual widgets](https://community.algolia.com/instantsearch.js/react/guide/Virtual_widgets.html) without having the need of saving the search state. 

As a workaround for now, the way to go is by using [virtual widgets](https://community.algolia.com/instantsearch.js/react/guide/Virtual_widgets.html) along with the [searchState and onSearchStateChange](https://community.algolia.com/instantsearch.js/react/guide/%3CInstantSearch%3E.html) props to save the search state except when the modal is closing. 

Here's an example: 

```js
 <View style={styles.maincontainer}>
        <InstantSearch
          appId=""
          apiKey=""
          indexName=""
          searchState={this.state.searchState}
          onSearchStateChange={searchState => {
            if (!this.state.isClosing) {
              this.setState({searchState}); //save the searchState except when the modal is closing
            } else {
              this.setState({isClosing: false}); 
            }
          }}
        >
          <ConnectedSearchBox/>
          <VirtualRefinementList attributeName="category" />

          <TouchableHighlight onPress={() => {
            this.setModalVisible(true);
          }}>
            <Text>Show Modal</Text>
          </TouchableHighlight>

          <Modal
            animationType={'slide'}
            transparent={false}
            visible={this.state.modalVisible}
            onRequestClose={() => this.setState({isClosing: true})}
          >
            <View style={{flex: 1, marginTop: 30}}>
              <ConnectedRefinementList attributeName="category" />
              <TouchableHighlight onPress={() => {
                this.setState({isClosing: true});
                this.setModalVisible(!this.state.modalVisible);
              }}>
                <Text>Hide Modal</Text>
              </TouchableHighlight>
            </View>
          </Modal>

          <ConnectedHits/>

        </InstantSearch>
</View>

```

where VirtualRefinementList is:

```js
const VirtualRefinementList = connectRefinementList(() => null);
```

**Comment by Arcade1080** [comment] 2017-04-06 11:24
@mthuret thank you so much, that works great. However, there seems to be a problem if i try this with a connectHierarchicalMenu, see the follwing example: 

```
const ConnectedHierarchicalMenu = connectHierarchicalMenu(Categories);
const VirtualHierarchicalMenu = connectHierarchicalMenu(() => null);

const ConnectedSizes = connectRefinementList(Sizes);
const VirtualSizes = connectRefinementList(() => null);

const ConnectedBrands = connectRefinementList(Brands);
const VirtualBrands = connectRefinementList(() => null);

const ConnectedCondition = connectRefinementList(Condition);
const VirtualCondition = connectRefinementList(() => null);


 <InstantSearch
    appId="VPHQ9I27FT"
    apiKey="296c02418086ba764e4afede02b34fe6"
    indexName='test_MAMIWELT_PRODUCT'
    searchState = {this.props.searchState}

    onSearchStateChange={searchState => {
                
      if (!this.state.isClosing) {
        this.props.setSearchState(searchState); //save the searchState except when the modal is closing
      } else {
        this.setState({isClosing: false}); 
      }
    }}
  >
 
    <TouchableOpacity onPress = { () => this.setModalVisible(true) }>
      <Text> Show Modal </Text>
    </TouchableOpacity>

    <Modal
      animationType={'slide'}
      transparent={true}
      visible={ this.state.filterExpanded }
      onRequestClose={() => this.setState({isClosing: true})}
    >
      <ScrollView style={{flex: 1, marginTop: 30}}>
        <TouchableHighlight onPress={() => {
          this.setState({isClosing: true});
          this.setModalVisible(false);
        }}>
          <Text>Hide Modal</Text>
        </TouchableHighlight>

        <ConnectedCurrentRefinements />
        <ConnectedHierarchicalMenu attributes = {['categories.level0', 'categories.level1']} />
        <ConnectedSizes attributeName = "size_tid"  />
        <ConnectedBrands attributeName = "brand_tid"  />
        <ConnectedCondition attributeName = "condition"  />

      </ScrollView>
    </Modal>
    
    <VirtualHierarchicalMenu attributes={['categories.level0','categories.level1']} />
    <VirtualSizes attributeName="size_tid" />      
    <VirtualBrands attributeName="brand_tid" />      
    <VirtualCondition attributeName="condition" />   

    <ConnectedHits/> 

</InstantSearch>
```
The follwing error is displayed: Cannot declare two hierarchical facets with the same name: `categories.level0`

Any ideas?

**Comment by Arcade1080** [comment] 2017-04-07 09:38
@mthuret, @Haroenv, @vvo 

here is the error message displayed by rn: 

<img width="358" alt="error_msg" src="https://cloud.githubusercontent.com/assets/4496916/24794615/8ceee2e4-1b86-11e7-9a30-daf62bb10e42.png">

**Comment by mthuret** [comment] 2017-04-11 13:28
Maybe you can mount the virtual widgets only if the modal is not shown?

Also I will close this as we moved the react-instantsearch repo here https://github.com/algolia/react-instantsearch. 

Reopen the issue there if it's still not working :)

**Closed by mthuret** 2017-04-11 13:28 UTC
Labels: ◾ react-instantsearch, ☎️  React Native, ❔ Question

**Comment by Arcade1080** [comment] 2017-04-11 14:36
Thank you! Will do!
