### ISSUE TITLE
connectors: call `unmountFn` with the same data as to render

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch.js#3072] opened 2018-08-20 16:02 UTC
**Is your feature request related to a problem? Please describe 🙏**
If you want to implement an unmounting, you're forced to wrap the widget into a function, like done in the regular widgets, but it would be nice if that wasn't necessary

**Describe the solution you'd like 🤔**
Pass the data that's passed to render to unmountFn

**Describe alternatives you've considered ✨**
Something else that I was thinking of (to get rid of the function for mapping, pretty confusing) would be to accept any number of arguments to the connector, that would then be passed to the renderFn and also the unmountFn. 

That way we don't need the "customRenderer" abstraction

**Additional context**
I was writing a guide for a custom infiniteHits and I wrote "you can use it as the regular functions", but you can't simply do that

**Comment by bobylito** [comment] 2018-08-22 09:53
Duplicate of #2843

**Closed by bobylito** 2018-08-22 09:53 UTC
