### ISSUE TITLE
Price slider stuck on mobile

### ISSUE THREAD

**Issue by JanPetr** [algolia/instantsearch.js#1186] opened 2016-08-11 08:30 UTC
Sometimes when you refine results by price slider on mobile device, it got stuck and you cannot scroll the page anymore and all scrolling you do just updates slider values.
Clicking on other elements on the page does not help.

Found on https://magento.algolia.com/catalogsearch/result/?q=pants
Reproduced on iPhone 5S, Safari

**Comment by Morhaus** [comment] 2016-08-11 08:42
Reproduced on iPhone 6, Safari. This seems to happen when using multiple fingers at once.

Might be related to https://github.com/leongersen/noUiSlider/issues/663

**Comment by vvo** [comment] 2016-08-24 11:59
Yes seems to be related to nouislider

**Comment by imshinto** [comment] 2016-10-31 11:43
We also have the same issue . And also the slider is also not smooth.

**Comment by vvo** [comment] 2016-11-02 16:31
As for "Interface becomes unresponsive when multiple touch used to refine the slider on mobile" I have a fix ready that just disables multi touch for this slider.

If you are all in for this @imshinto @dustincoates @JanPetr I can do this. It's the best I can do for now.

**Comment by vvo** [comment] 2016-11-02 16:32
Reference PR on nouislider repo: https://github.com/leongersen/noUiSlider/pull/649

**Comment by imshinto** [comment] 2016-11-02 16:45
That would be great @vvo .

**Comment by vvo** [comment] 2016-11-02 17:25
@imshinto will be released tomorrow morning (CET) so that I can follow the release and watch for any issue.

Consider this (particular issue) fixed tomorrow noon CET.

**Closed** 2016-11-03 10:16 UTC
Labels: ❤ Bug
