### ISSUE TITLE
Doc website: Visual bugs on Firefox on SVG

### ISSUE THREAD

**Issue by ElPicador** [algolia/instantsearch.js#2666] opened 2018-01-22 17:49 UTC
**Bug: What is the current behavior?**
A lot (all ?) of SVG images do not display properly on Firefox
<img width="329" alt="screenshot 2018-01-22 18 47 39" src="https://user-images.githubusercontent.com/16667/35235573-dbc47480-ffa4-11e7-8f63-79c05ac36fb3.png">

<img width="285" alt="screenshot 2018-01-22 18 47 51" src="https://user-images.githubusercontent.com/16667/35235574-dc0e015e-ffa4-11e7-9a36-9a500240ab05.png">

**Bug: What is the expected behavior?**
To have the same visuals as in Chrome 😛 

**Bug: What browsers are impacted? Which versions?**
Firefox 57

**Comment by iam4x** [comment] 2018-01-23 14:25
I think @Haroenv tweeted on this issue for another website?

**Comment by Haroenv** [comment] 2018-01-23 15:12
If they are background images, we should be able to replace # by %23, otherwise I'm not sure what the issue is 🤔

**Comment by bobylito** [comment] 2018-01-25 10:34
Thanks for reporting this issue @ElPicador. This is a duplicate of #2536. Since @LukyVj doesn't have much bandwidth, maybe @ronanlevesque could have a look?

**Closed** 2018-02-02 09:06 UTC
Labels: Doc: website
