### ISSUE TITLE
Uncaught TypeError: y is not a function - bundled version of preact@10.0.5 errors when executing code compiled with Webpack

### ISSUE THREAD

**Issue by markhealey** [algolia/instantsearch.js#4235] opened 2019-12-06 19:12 UTC
**Describe the bug 🐛**
We just upgraded InstantSearch from 3.x to 4.0.1 and have everything working great...except in production where our code is compiled _and minified_ using Webpack with Terser.

When using `search.addWidgets([...])`, instantsearch invokes `preact` code which causes the TypeError shown below.

![image](https://user-images.githubusercontent.com/22938/70348832-c2890080-1820-11ea-9aad-2189bddc6217.png)

Don't ask me why but downgrading to exactly `preact@10.0.1` makes the issue go away.

**To Reproduce 🔍**
1. instantsearch@4.0.1, preact@10.0.5 (or really any version > 10.0.1)
2. Compile code with gulp webpack-stream 5.2.1 using latest Terser plugin minimizer with default settings
3. Use `search.addWidgets` (need to be at least 1 `refinementList` widget) to trigger preact code
4. Load page

**Comment by Haroenv** [comment] 2019-12-09 08:48
Hey  @markhealey, do you think you  could reproduce this in codesandbox or in a repository? We have not seen an error like that yet, so I don't know what could be the cause of this. Thanks!

We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

**Comment by Haroenv** [comment] 2019-12-20 10:25
I hope this is fixed for you with any of the more recent versions than 4.0.1. I'll close this issue now, since I didn't hear back from you, and can't reproduce this.

**Closed by Haroenv** 2019-12-20 10:25 UTC
