### ISSUE TITLE
hierarchicalMenu - Let users know that a particular facet value (category) has children

### ISSUE THREAD

**Issue by shramee** [algolia/instantsearch.js#2867] opened 2018-04-08 07:30 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature request

**Feature: What is your use case for such a feature?**

Well, we'd really like to let our users know that particular categories have children, at the moment their seems to be no way to do it easily... Not sure it can be done even with a custom widget using `connectHierarchicalMenu` connector.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

Well, not sure I understand this right but I think would be nice to have something like `hasChildren` or `childrenCount` available as a property on arguments object passed to `item` callback for `HierarchicalMenuTemplates`.
https://community.algolia.com/instantsearch.js/v2/widgets/hierarchicalMenu.html#struct-HierarchicalMenuTemplates

**What is the version you are using? Always use the latest one before opening a bug issue.**

v1.11.7

**Comment by Haroenv** [comment] 2018-04-09 07:54
See also https://github.com/algolia/instantsearch.js/issues/818 and https://github.com/algolia/instantsearch.js/pull/2638, the problem is that this would require us to do an extra query for each hierarchical item, which wouldn't be an ideal tradeoff.

**Comment by dhayab** [comment] 2022-12-21 10:34
Closing this issue in favor of https://github.com/algolia/instantsearch.js/discussions/5098 which has more activity.

**Closed by dhayab** 2022-12-21 10:34 UTC
Labels: Scope: Connectors, Feedback, Type: Feature
