### ISSUE TITLE
Unable to minify instantsearch.js using YUI compressor

### ISSUE THREAD

**Issue by scssyworks** [algolia/instantsearch.js#3202] opened 2018-10-16 10:02 UTC
**Describe the bug 🐛**
YUI compressor gives error when minifying instantsearch.js. This is the uncompressed file available in dist folder which we are referring to.

**To Reproduce 🔍**
1. Go to https://www.piliapp.com/minify/yui-compressor/
2. Copy and paste instantsearch.js code in the text field
3. Click compress
4. Minification fails

**Expected behavior 💭**
The code should minify.

**Additional context**
We use Adobe Experience Manager which uses YUI compressor. Our workflow requires us to use unminified versions of JS files as minification is directly done by AEM server. Using unminified version also doesn't work as minification is enabled at the server.

**Comment by Haroenv** [comment] 2018-10-17 10:55
Hey, we found where the issue is. The error happens because we build our files in ES5, not in ES3. 

Steps you need to take to transform our code into ES3:

1. install babel
2. add the plugins: `'babel-plugin-transform-es3-property-literals', 'babel-plugin-transform-es3-member-expression-literals', '@babel/plugin-transform-reserved-words',`
3. run babel on InstantSearch

Then only after that, YUI compressor will be happy and work.

**Comment by Haroenv** [comment] 2018-10-17 11:00
Easiest route: give up on trying to minify with YUI, find some way to disable it, since our source is already minified. Maybe it won't be minified if you load it via CDN for example. 

I'll close this issue now, since I don't see a working solution or reason to use YUI compressor. 

Thanks, please still get back to give more info if you got it to work some way

**Closed by Haroenv** 2018-10-17 11:00 UTC
Labels: hacktoberfest

**Comment by Haroenv** [comment] 2018-10-28 10:00
In fact, YUI compressor can only deal with ES3, not ES5 (I tried it myself). No current browser has the behavior of throwing errors on code like exports.default or default, and some other words inside object literals. I think your best option will be to turn off compression with YUI in AEM dashboard. 

The problem is that YUI is acting like IE8, not like any recently released browser, and thus can't be supported. The babel steps I listed higher are a first step, but still likely not enough to make it minifyable. We have a minified version of InstantSearch available on CDNs, so there shouldn't be a need to reminify yourself 

See https://helpx.adobe.com/experience-manager/kb/how-to-change-the-minification-engine-for-client-libraries-in-AEM.html for more info!
