### ISSUE TITLE
Select multiple categories within a HierarchicalMenu

### ISSUE THREAD

**Issue by nicholasmaddren** [algolia/instantsearch.js#3387] opened 2018-12-30 12:50 UTC
**Describe the solution you'd like 🤔**

I'd really like to create a HierarchicalMenu that allows me to select multiple categories instead of switching between categories when I click different links. Much like this example:

<img width="278" alt="screen shot 2018-12-30 at 12 41 15" src="https://user-images.githubusercontent.com/28411024/50547358-4e1d0900-0c30-11e9-866e-f2663ee397a0.png">

I guess you could say this a RefinementList within a HierarchicalMenu.

**Describe alternatives you've considered ✨**

I originally tried using HierarchicalMenu but it doesn't give my users the best user experience because they would like to select multiple categories instead of returning the results for one category each time.

If there is any information to do this already that I haven't already stumbled across that would be great help.

**Comment by samouss** [comment] 2018-12-30 18:51
Duplicate of #1658.

**Closed by samouss** 2018-12-30 18:51 UTC
