### ISSUE TITLE
The RangeSlider doesnt seem to adhere to the given precision for the halfway point

### ISSUE THREAD

**Issue by fruitl00p** [algolia/instantsearch.js#3354] opened 2018-12-14 15:36 UTC
**Describe the bug 🐛**
If we pass a `precision` of 0 to the range slider (and a `step` of 1) I would expect that the halfway point would be a whole number. But the halfway indicator isn't rounded (somewhere around `computeDefaultPitPoints`)

![image](https://user-images.githubusercontent.com/1492861/50012096-0d7d8880-ffbe-11e8-9bd0-0ef2c356a7e3.png)

This is a yearly slider where i would have expected either 2003 or 2004 halfway.. :)

**To Reproduce 🔍**
1. Add a rangeSlider widget from the correct index without any furter configuration (since the defaults should be a precision of 0 and step can even be neglegted)

**Expected behavior 💭**
I guess some sort of whole number would be nice :) Or an option to manipulate the exact presentation?

**Environment:**
 - Version 2.10.4 of instantsearch.js

Thanks!

**Comment by samouss** [comment] 2018-12-14 16:12
Duplicate of https://github.com/algolia/instantsearch.js/issues/2828

Related to https://github.com/algolia/instantsearch.js/issues/2786

**Closed by samouss** 2018-12-14 16:12 UTC
