### ISSUE TITLE
Support multiple Configure components?

### ISSUE THREAD

**Issue by zackify** [algolia/instantsearch.js#2006] opened 2017-02-24 20:35 UTC
**Do you want to request a *feature* or report a *bug*?**
Both

**Bug: What is the current behavior?**
Rendering a second configure does nothing.

**Bug: What is the expected behavior?**
For the props to be merged into the search state

**Feature: What is your use case for such a feature?**

I need to show a refinement for a search radius. This only gets shown once a location is selected, which sets a bounding box on the search state. Now the user can select one of three radius's which are added to a second configure with the prop `radius`. Is there a better way to add a radius refinement?

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**
3.2.1

**Comment by mthuret** [comment] 2017-02-26 13:03
Hi @zackify,

I'll need to check why having two Configure at the same time isn't working, because it should.

However, the Configure widget can take several search parameters. Can you try to just add the `radius` one as a prop of your first Configure widget, when needed?

**Comment by zackify** [comment] 2017-02-27 18:30
Hmm, debugging it a little more shows me that it does in fact apply the search state from both, but onSearchState change is not updated when the second Configure's props change. So the app updates the search, but the url won't update

**Comment by mthuret** [comment] 2017-02-27 19:42
No, everything should be under one configure. I still didn't have the time to have a look at it but will and let you know. 

In the meantime, did you try having only one Configure and just play with the props?

**Comment by mthuret** [comment] 2017-04-11 13:29
React InstantSearch has been moved here: https://github.com/algolia/react-instantsearch
This issue has either been rewritten or placed inside our backlog.

**Comment by mthuret** [comment] 2017-04-19 09:11
@zackify I wasn't able to reproduce this bug anymore using our 4.0.0-beta.2 version. 

Here's an example of what I'm doing to reproduce this issue, and this is working.

```js
class ConfigureExample extends React.Component {
  constructor() {
    super();
    this.state = { hitsPerPage: 3 };
  }

  onClick() {
    const hitsPerPage = this.state.hitsPerPage === 3 ? 1 : 3;
    this.setState({ hitsPerPage });
  }

  render() {
    const hitsPerPage = <Configure hitsPerPage={this.state.hitsPerPage} />;
    const facets = this.state.hitsPerPage === 3
      ? <Configure filters="category:Bathroom" />
      : <Configure filters="category:Lighting" />;

    return (
      <WrapWithHits linkedStoryGroup="Configure">
        {hitsPerPage}
        {facets}
        <button onClick={this.onClick.bind(this)}>Toggle HitsPerPage</button>
      </WrapWithHits>
    );
  }
```

I will close this issue, please reopen it if you still have an issue while using multiple configure.

**Closed** 2017-04-19 09:11 UTC
Labels: Configure, ◾ react-instantsearch, ❔ Question
