### ISSUE TITLE
allItems template shouldn't be available in infiniteHits

### ISSUE THREAD

**Issue by jvreeken** [algolia/instantsearch.js#2543] opened 2017-10-31 16:25 UTC
Hits allows for the allItems template which allows for greater customization of the templates, for example inside tables and so forth...

When the allItems template is used with infiniteHits, its doesn't give any error, but instead of adding the newly loaded items, it replaces everything with the new page of results.

**Comment by Haroenv** [comment] 2017-11-01 09:15
Thanks for making an issue, feel free to read more in #2519

duplicate of 2519

**Comment by bobylito** [comment] 2017-11-01 13:59
> When the allItems template is used with infiniteHits, its doesn't give any error, but instead of adding the newly loaded items, it replaces everything with the new page of results.

The fact that you can use the allItems is a bug :/ https://community.algolia.com/instantsearch.js/v2/widgets/infiniteHits.html#struct-InfiniteHitsTemplates

**Comment by Haroenv** [comment] 2017-11-01 14:00
Oh that’s right, I’m sorry, I read this as a duplicate

**Closed** 2018-05-29 09:17 UTC
Labels: ❤ Bug, 🔄 Scope: widgets
