### ISSUE TITLE
transformData in the Hits widget is called when no results

### ISSUE THREAD

**Issue by seafoox** [algolia/instantsearch.js#832] opened 2016-02-09 13:35 UTC
In the Hits widget, when there is no result for a search query `hits.lengths === 0`, then the function declared under `transformData` remains called. I guess in the case there is no result, we don't expect that method to get called. One parameter is then passed to it, no anymore one of the hits, but the whole content object obtained as a result of the search API call.

**Comment by vvo** [comment] 2016-03-02 15:57
The issue is maybe a documentation issue because even if it worked, we do not document anymore to use transformData: function(){}. It's either transformData.hits or transformData.empty (no results).

We could also just throw when we have a transformData: function() {} passed.

**Comment by pixelastic** [comment] 2016-03-03 11:11
`transformData: () => {}` is a shortcut to `transformData: { hits: () => {} }`

Removing support for the shortcut notation will surely break a lot of implementations (starting with our own demos and tutorials). I think it needs to be better explained in the documentation, but not removed.

**Comment by vvo** [comment] 2016-03-03 11:12
But we do not document it since a long time right? So the number of implementations relying on it should be small?

**Comment by vvo** [comment] 2016-03-03 11:14
In the end, the current behavior is not really triggering any issue right? Sure the behavior is weird but its not advised anywhere to use transformData this way. So we can just close this I believe. Next version should just not accept this

**Closed by vvo** 2016-03-03 11:14 UTC
Labels: question
