### ISSUE TITLE
In requestBuilder._getFacetFilters when state.hierarchicalFacetsRefinements is parsed - it only process the first element/value

### ISSUE THREAD

**Issue by ferhan01** [algolia/instantsearch.js#4333] opened 2020-02-10 10:12 UTC
**Our issue:**

We have the following situation:
- A brand menu filter (HierarchicalMenu widget), which contains root brands and their sub-categories.
- It seems that HierarchicalMenu menu allows faceting by only one value - currently selected option.
- We have a use case where we need to add one or more additional values to the above one - in particular - to filter by the selected brand/sub-brand and in addition with `None` (adding OR filter).
- We tried to use `onSearchStateChange` to inject dynamically the additional facet filter, but seems that does not works for `HierarchicalMenu` since it only process the first element from `state.hierarchicalFacetsRefinements`.
- Also in case of fixing the above, consider changing the behaviour of the HierarchicalMenu widget as well - to support multi-values selection.

Our widget looks like this:
```
 <HierarchicalMenu
     key="brandMenu"
     attributes={['brand.lvl0', 'brand.lvl1']}
     separator="/"
     defaultRefinement={defaultRefinement}
     showParentLevel
  />
```                  
and 

```
class App extends Component {
   constructor(props) {

  ............

      this.searchParams = {
        hitsPerPage: 60,
        disjunctiveFacetsRefinements,
        filters,
        facetFilters
      };
    }

.............

  handleSearchStateChange(nextSearchState) {
    if (!this.mounted) {
      return;
    }
    onSearchStateChange(nextSearchState);

    const dynamicBrandFilters = ['brand.lvl0:None'];

    this.searchParams.facetFilters = {
      ...this.searchParams.facetFilters,
      ...dynamicBrandFilters,
    };
    
    this.setState({ searchState: nextSearchState });
  }
}
```

and
```
 <InstantSearch
   searchClient={this.algoliaClient}
   indexName={this.props.indexes.products}
   searchState={this.state.searchState}
   onSearchStateChange={this.handleSearchStateChange}
   resultsState={this.resultState}
 >
<Configure {...this.searchParams} />
```

**Expected behaviour:**
- We can dynamically add one or more additional (`OR`) facet filters to the  `HierarchicalMenu` current refinement, using `onSearchStateChange`.

Looking forward for any feedback or suggestion to workaround this (if possible).

Thank you in advance!

**Comment by francoischalifour** [comment] 2020-02-10 13:00
What you're trying to achieve seems to be a "disjunctive hierarchical menu". This feature is not supported in our [JavaScript Helper](https://github.com/algolia/algoliasearch-helper-js) (the underlying library that manages the state) because it would trigger too many requests to the Algolia API.

If despite this technical constraint you'd still like to implement this feature, the only solution as of now would be to see how the Helper manages hierarchical facets and to support multiple selections in a custom hierarchical menu widget.

Closing because duplicate of #1658. You can subscribe to this issue to be notified when we plan to support this feature.

**Closed by francoischalifour** 2020-02-10 13:00 UTC
