### ISSUE TITLE
Importing Instant Search into Angular 2 CLI

### ISSUE THREAD

**Issue by lebsral** [algolia/instantsearch.js#2073] opened 2017-03-23 16:33 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG
<!--
  ***************************
  If the current behavior is a bug, please provide all the steps to reproduce and a minimal
  [JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
  and `npm start`.
  https://github.com/KillionCorp/AngularAlgolia
also see the discussion here
https://discourse.algolia.com/t/instant-search-for-angular-2-cli-based-project/785/7

**Bug: What is the current behavior?**
Importing instantsearch.js causes errors that look like this:

ERROR in ./~/instantsearch.js/dist-es5-module/src/components/Template.js

**Bug: What is the expected behavior?**
correct import

**Bug: What browsers are impacted? Which versions?**
Chrome Version 56.0.2924.87 (64-bit)

**What project are you opening an issue for?**
- instantsearch.js

**What is the version you are using? Always use the latest one before opening a bug issue.**
"instantsearch.js": "^1.11.3",

my system info:

larsb-syntax:AngularAlgolia larsb$ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0-rc.1
node: 6.10.0
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.10

global installs 
typescript@2.2.1
typings@2.1.0
npm@4.3.0

error on serve
```
Last login: Thu Mar 23 12:08:46 on ttys002
larsb-syntax:AngularAlgolia larsb$ ng serve
** NG Live Development Server is running on http://localhost:4200 **
Hash: e48559f1692d4515b49f                                                               
Time: 9005ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 157 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 6.53 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 20.9 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.06 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js
Module not found: Error: Can't resolve 'lodash/forEach' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/lib'
 @ ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js 19:15-40
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/instantsearch.js/dist-es5-module/src/widgets/search-box/search-box.js
Module not found: Error: Can't resolve 'lodash/forEach' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/widgets/search-box'
 @ ./~/instantsearch.js/dist-es5-module/src/widgets/search-box/search-box.js 11:15-40
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js
Module not found: Error: Can't resolve 'lodash/mergeWith' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/lib'
 @ ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js 23:17-44
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js
Module not found: Error: Can't resolve 'lodash/union' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/lib'
 @ ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js 27:13-36
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js
Module not found: Error: Can't resolve 'lodash/clone' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/lib'
 @ ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js 31:13-36
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js
Module not found: Error: Can't resolve 'lodash/isPlainObject' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/lib'
 @ ./~/instantsearch.js/dist-es5-module/src/lib/InstantSearch.js 35:21-52
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/instantsearch.js/dist-es5-module/src/widgets/current-refined-values/current-refined-values.js
Module not found: Error: Can't resolve 'lodash/isPlainObject' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/widgets/current-refined-values'
 @ ./~/instantsearch.js/dist-es5-module/src/widgets/current-refined-values/current-refined-values.js 37:21-52
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/instantsearch.js/dist-es5-module/src/widgets/current-refined-values/current-refined-values.js
Module not found: Error: Can't resolve 'lodash/isUndefined' in '/Users/larsb/Documents/mycode/AngularAlgolia/node_modules/instantsearch.js/dist-es5-module/src/widgets/current-refined-values'
 @ ./~/instantsearch.js/dist-es5-module/src/widgets/current-refined-values/current-refined-values.js 21:19-48
 @ ./~/instantsearch.js/dist-es5-module/src/lib/main.js
 @ ./~/instantsearch.js/dist-es5-module/index.js

```

**Comment by Haroenv** [comment] 2017-03-23 16:37
see https://github.com/KillionCorp/AngularAlgolia

**Comment by lebsral** [comment] 2017-03-23 17:04
A couple of thoughts/suggestions:

in .angular-cli.json  perhaps something like this would be helpful?
    ```
 "scripts": [
        "../node_modules/instantsearch.js/dist/instantsearch.js"
      ],
```

https://github.com/angular/angular-cli/wiki/stories-third-party-lib
Does instantsearch.js need typings?

http://stackoverflow.com/questions/39915178/how-does-angular-cli-work-with-es6-modules

**Comment by vvo** [comment] 2017-03-23 21:51
linked disourse post: https://discourse.algolia.com/t/instant-search-for-angular-2-cli-based-project/785

**Comment by lebsral** [comment] 2017-03-24 20:04
is this the direction things need to change to?
[Make an angular module](https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464#.fpa550gby)

**Comment by Haroenv** [comment] 2017-03-24 20:07
Thanks for your research. We really want to make this work, so if you find things that work, we'll gladly merge it, but didn't get a good solution yet

**Comment by Bengejd** [comment] 2017-06-15 17:01
Any update on when this will be fixed? I am running into the same issue with AutoComplete.js with Algolia.

**Comment by vvo** [comment] 2017-06-16 08:01
@Bengejd Thanks for getting back here, the more feedback we get on Angular, the better because we might give better tooling around Angular in the future.

Right now we need a reproducible way to understand your bug, for example a GIT repository where we can do npm install, npm start and if it fails, try to fix it for you.

**Comment by foufrix** [comment] 2017-06-30 15:04
I'm using angular 4 and importing looks like working with 

npm install instantsearch.js --save

and in the ts  : 
import * as instantsearch from 'instantsearch.js';

Dunno if it's the problem here

**Comment by Haroenv** [comment] 2017-06-30 15:06
Can you make an example project @foufrix, that would be really helpful ❤️

**Comment by codediodeio** [comment] 2017-07-17 19:27
Here's a working example in Angular 4.3. 

https://gist.github.com/codediodeio/8b8b22844f8fd8a34ff6d6a6e8582468

**Comment by Haroenv** [comment] 2017-07-18 08:12
Thank you @codediodeio, that really helps!

**Comment by foufrix** [comment] 2017-07-18 08:28
Thank you very much ! i'll take a look at it !

**Comment by darthsitthiander** [comment] 2017-09-21 21:07
This didn't work for me on Angular 4.4. Also I get everything but pagination working there. 

`   // const widget = connectPagination();
    // this.instantSearchService.search.addWidget(widget());`

That's roughly how I tried, based on the search and hits I have got working:

` [...]
template: `
  <div class="is-hits-root">
    <ul class="row">
      <li *ngFor="let hit of state.hits" class="col xl3 l4 m6 s12">
        <app-object key="{{hit.objectID}}" name="{{hit.name}}" price="{{hit.price}}" typeId="{{hit.type}}" routerLinkBase="{{ routerLinkBase }}"></app-object>
      </li>
    </ul>
    <div *ngIf="state.hits.length == 0">{{ 'offers-none' | translate }}</div>
  </div>
`,
[...]
   var customHits = connectHits(this.updateState);
    
    // mount widget on the page
    this.instantSearchService.search.addWidget(
      customHits()
    );`

**Comment by Haroenv** [comment] 2017-09-22 07:25
Hey @darthsitthiander, I assume you saw [the guide](https://community.algolia.com/instantsearch.js/v2/guides/angular-integration.html) we made, since you seem to use similar terminology. 

However, I'm not sure if what you posted in this thread is enough to make it clear what the actual issue is you're facing, can you make a complete example, based on the one we made in the guide, and explain where something goes wrong? Thanks!

P.S.: For anyone visiting this thread, we're currently making a version of InstantSearch, just for Angular, please fill in [this form](https://goo.gl/forms/US09OkyYKByeF1W53) if you want to be contacted when we make a beta version available.

**Comment by darthsitthiander** [comment] 2017-09-22 12:26
Dear Haroen,

Thank you very much for reaching out to me so directly. I will try to
reproduce this in a separate project and provide it as soon as I can. I'll
post it in the thread same as before.

Have a nice day!

**Comment by darthsitthiander** [comment] 2017-09-22 14:09
@Haroenv thanks for the form. I just registered and am curious of how the project will progress. 

Mostly I used the link you provided to get started and made my way from there. Also I made a [sample project](https://github.com/darthsitthiander/algolia-instantsearch) displaying my issue. Of course I removed my credentials since the project on GitHub is public. Please edit them in the InstantSearchService. Once I use the tags for the pagination, everything but the SearchBox disappears.

Thanks for your help!

**Comment by Haroenv** [comment] 2017-09-22 14:41
Thanks @darthsitthiander, we'll get back to you

**Comment by iam4x** [comment] 2017-09-27 13:10
@darthsitthiander I've looked to your repo, you did not take the same approach as the others components you implemented. You need to follow this kind of pattern without references to jQuery in your DOM operations.

And here is a correct pagination component for AngularJS:

```ts
import { Component, OnInit } from '@angular/core';
import { InstantSearchService } from '../../services/instantsearch.service';
import { connectPagination } from 'instantsearch.js/connectors';

@Component({
  selector: 'app-pagination',
  template: `
    <div class="is-pagination-root">
      <ul>
        <li
          *ngFor="let page of pages"
          (click)="state.refine(page)"
          [ngClass]="{'active': page === state.currentRefinement}"
        >
          {{page + 1}}
        </li>
      </ul>
    </div>
  `,
  styles: [`
    ul, li {
      margin: 0;
      padding: 0;
      display: inline-block;
    }

    li {
      cursor: pointer;
      margin-right: 5px;
    }

    li.active {
      color: red;
      font-weight: bold;
    }
  `]
})
export class PaginationComponent implements OnInit {
  state: {
    currentRefinement: number,
    nbPages: number,
    refine: Function
  } = {
    currentRefinement: 0,
    nbPages: 0,
    refine: () => {}
  };

  constructor(private instantSearchService: InstantSearchService) {}

  get pages(): number[] {

    return Array
      .apply(null, {length: this.state.nbPages})
      .map(Number.call, Number)
  }

  ngOnInit() {
    const widget = connectPagination(this.updateState);
    this.instantSearchService.search.addWidget(widget({ maxPages: 10 }));
  }

  updateState = (state, isFirstRendering) => {
    if (isFirstRendering) {
      return Promise.resolve(null).then(() => {
        this.state = state;
      })
    }

    this.state = state;
  }
}
```

Anyway, like @Haroenv said we are planning a real angular-instantsearch library to simplify the usage 👍

**Comment by darthsitthiander** [comment] 2017-09-27 13:29
@iam4x Thanks a bunch, it finally works! I was searching for this code for a long time, but obviously not good enough. Just updated the repo as well. I'll be looking into the library once it gets released, thanks! :)

**Comment by bobylito** [comment] 2017-10-18 11:24
Looks like this bug is sorta fixed. Reopen it if you think I'm wrong :)

**Closed by bobylito** 2017-10-18 11:24 UTC
Labels: ❔ Investigate, ❤ Bug
