### ISSUE TITLE
Laravel 5.4 module not found

### ISSUE THREAD

**Issue by object505** [algolia/instantsearch.js#2153] opened 2017-05-18 11:10 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**Bug: What is the current behavior?**
I have installed instantsearch via npm.
I am importing it like this:
`window.instantsearch = require('instantsearch.js');`

When I run `npm run dev` I am getting the following error:
        `This relative module was not found:`
`* ./src/lib/main.js in ./~/instantsearch.js/dist-es5-module/index.js`

Any ideas why is this happening?

**What is the version you are using? Always use the latest one before opening a bug issue.**
Latest, v1.11.10

**Comment by Haroenv** [comment] 2017-05-18 11:17
Ah, I think I found what the issue is, related to #2150

**Comment by Haroenv** [comment] 2017-05-18 11:18
fixed in v.1.11.11

**Closed by Haroenv** 2017-05-18 11:18 UTC
Labels: ❤ Bug

**Comment by Haroenv** [comment] 2017-05-18 11:28
Do you get an error in the console, but it still works, with 1.11.11 @object505, if so, please reopen this issue.

**Comment by object505** [comment] 2017-05-18 11:32
@Haroenv Yes, I am getting this error:
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`
