### ISSUE TITLE
How can I refine my search from URL query string

### ISSUE THREAD

**Issue by ankitachetu** [algolia/instantsearch.js#2668] opened 2018-01-22 18:44 UTC
How can I refine my search from URL query string, so that whatever color I want to select by default can be selected from URL through query string.

Example : http://*********/shop/desk-accessories/desk-pads/?refinement=color:black

The above URL should auto select from my selected result for black color.

**Comment by Haroenv** [comment] 2018-01-22 19:14
Did you check out the urlSync option in the InstantSearch initialiser? 

https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-InstantSearchOptions-urlSync

See also: https://github.com/algolia/instantsearch.js/pull/2636

**Comment by ankitachetu** [comment] 2018-01-22 19:18
Thanks Haroenv.
Can you suggest the same when we click on any filter option the same should be binded in URL so that we can copy the URL and forward to our customer based on our selection.

**Comment by iam4x** [comment] 2018-01-23 14:24
Hello @ankitachetu if you set `urlSync` to true, this should be already the case, you will be able to share URLs

**Comment by Haroenv** [comment] 2018-01-24 10:56
duplicate of https://github.com/algolia/react-instantsearch/issues/895

**Closed by Haroenv** 2018-01-24 10:56 UTC
