### ISSUE TITLE
[urlSync] input lose focus

### ISSUE THREAD

**Issue by maxiloc** [algolia/instantsearch.js#126] opened 2015-09-24 08:33 UTC
When you type fast on the search input with url sync enable, sometimes you loose focus

**Comment by vvo** [comment] 2015-09-24 08:35
I believe this is linked to https://github.com/algolia/instantsearch.js/pull/95#discussion-diff-40193817R121 cc @bobylito Can we find another way to do this but blur? like you proposed in https://github.com/algolia/instantsearch.js/pull/95#discussion_r40197280

**Comment by vvo** [comment] 2015-09-24 08:35
(just reproduced it)

**Comment by bobylito** [comment] 2015-09-24 17:47
WHooooa that's extremly easy to reproduce :( :hamster:

**Comment by bobylito** [comment] 2015-09-25 08:10
This should only happen with hash, can you confirm?

**Comment by maxiloc** [comment] 2015-09-25 08:13
Never try without hash :smile:

**Comment by bobylito** [comment] 2015-09-25 08:23
OK no problem. Just to give more context. I indeed traced back the problem when we trigger the blur to all input. This is triggered because there is a "popstate" and the state is different. This popstate is correctly triggered in modern browsers with the use of history API, and it is triggered when the URL is manipulated directly in the bar or using back or forward history buttons. But it is emulated when we use the hash, using hashchange event. This is event is triggered whatever the way the url is modified. Because of that we make a test, but it is not full proof against fast typers, as the state in the helper keep being modified even though we don't have yet the search results :(

**Comment by bobylito** [comment] 2015-09-25 15:04
Ok so #131 should help here. Waiting for the merge :)

**Comment by vvo** [comment] 2015-09-28 11:58
Merged, getting it less but still getting it if I try.

**Comment by bobylito** [comment] 2015-09-28 12:19
Yes it's not done with #131 but it was required to have it merged first ;)

**Closed** 2015-09-30 22:23 UTC
Labels: bug, waiting for release
