### ISSUE TITLE
Search old results by one state

### ISSUE THREAD

**Issue by andrew-belyi** [algolia/instantsearch.js#4664] opened 2021-02-26 21:32 UTC
Hello!
I have an issue, which happens just on stage and production servers. On localhost everything works fine.
I’m using react-instantsearch-dom inside Next.js project.
The problem is that results, visible for a user, are old, they were fetched by previous search state, not by current one. In other words:
1) you see initial search page with all results
2) you type search query for a 1st time - nothing changed (but in this step results should be different)
3) you change search param/query again and see results from step 2 (in this step you already have 3rd SearchState)
4) you change something - create 4th SearchState, but see results from step 3

Like one step behind, hope I clearly explained it.
To my mind the problem is in connectInfiniteHits, because in console I see that Algolia made a correct request (by new SearchState, also url is updating correctly), in response there is a new portion of data, but inside connectInfiniteHits component I receive an old portion of data (by previous search state, not by current). It’s soooo bad for user experience and I don’t understand what is wrong.
      
Will be appreciate for any suggestion and help

**Comment by Haroenv** [comment] 2021-03-01 09:38
Looks like this is a duplicate of https://github.com/algolia/react-instantsearch/issues/3018, will handle there :)

**Closed by Haroenv** 2021-03-01 09:38 UTC
