### ISSUE TITLE
React dependency?

### ISSUE THREAD

**Issue by nilsi** [algolia/instantsearch.js#2482] opened 2017-10-15 09:36 UTC
Hi, 

I installed this library in a Meteor/Blaze app and got the following exception:

```
Unable to resolve some modules:
  "react" in /Users/user/repos/my_app/node_modules/instantsearch.js/dist-es5-module/src/widgets/toggle/toggle.js (web.browser)
  "react-dom" in /Users/user/repos/my_app/node_modules/instantsearch.js/dist-es5-module/src/widgets/toggle/toggle.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save react react-dom  
```
It works if I install it but do I really need to? I am not using react otherwise so prefer not having to install it just for instantsearch.

Thanks.

**Edit**: When I look into components I now see that most of them use React. I thought this project were meant for vanilla Javascript users where react-instantsearch is for React users.

**Comment by Haroenv** [comment] 2017-10-15 12:51
This is a duplicate of #2388. Basically we are using preact behind the scenes, which is aliased to React. The public API is exposed for apps that don’t use a framework.

**Closed by Haroenv** 2017-10-15 12:51 UTC
