### ISSUE TITLE
Weird behaviour when defining a facet that is used in a widget

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#1902] opened 2017-01-24 12:55 UTC
This bug was reported by a user on the [community forum](https://discourse.algolia.com/t/menu-widget-not-displaying-facets/426). 

The current behaviour is that if a facet is defined both in the search parameters of the instantsearch.js constructor and in the configuration of a menu widget, then the widget does not display values. When removing the facet from the search parameters, then the widget contains values.

https://jsfiddle.net/e6dd2496/1/

Try removing the facets from the search parameters, and the menu will contain values.

**Comment by timkelty** [comment] 2017-02-23 03:46
Just got bit by this one too.
It seems to be specific to the menu widget as far as I can tell.

Likely related - from what I can tell, all the other [filter type widgets](https://community.algolia.com/instantsearch.js/documentation/#filters) seem to add their attributes to `SearchParameters.facets` or `SearchParameters.disjunctiveFacets`. The menu widget does NOT do this, though it seems to me it should just like the others.

I discovered this when I got an error when I tried to add a facetRefinement on an attribute I was using a menu widget with: https://github.com/algolia/instantsearch.js/issues/2004

**Comment by timkelty** [comment] 2017-02-23 04:17
Another thing that seems broken about the menu widget:
If you add a refinement, the search results are properly filtered, but the menu widget's active style is not applied to the facet value.

In this example, "Music" should be bold, but isn't: https://jsfiddle.net/timkelty/u766n8ah/
Notice how the active state is set for the refinementList widget, but not for menu.

**Comment by timkelty** [comment] 2017-03-17 12:45
> In this example, "Music" should be bold, but isn't: https://jsfiddle.net/timkelty/u766n8ah/
Notice how the active state is set for the refinementList widget, but not for menu.

Seem to have figured out a piece of the puzzle: https://jsfiddle.net/timkelty/u766n8ah/2/
It appears the menu widget operates on `hierarchicalFacets`/`hierarchicalFacetsRefinements`, not `facets` or `disjunctiveFacets`.

**Comment by Haroenv** [comment] 2019-10-08 09:37
This behaviour is still acting the same way using a configure widget, now that `searchParameters` is no longer an option for v4. This pattern instead should be removed by replacing it with a real "initial value" API on each connector

**Comment by Haroenv** [comment] 2021-08-23 13:59
I don't really see the use case of manually setting `facets` for a managed facet. facets already merges with the existing parameters set by widgets, and in almost all cases, these parameters sound involved enough to be part of a custom widget instead of using solely configure, as there would be rendering involved too.

I'll close this issue now, but if anyone else in the future has a similar issue, please open a new issue with reproduction. Thanks for opening!

**Closed by Haroenv** 2021-08-23 13:59 UTC
Labels: Type: Bug, Scope: Widgets

**Comment by samholguin** [comment] 2021-10-13 18:59
> > In this example, "Music" should be bold, but isn't: https://jsfiddle.net/timkelty/u766n8ah/
> > Notice how the active state is set for the refinementList widget, but not for menu.
> 
> Seem to have figured out a piece of the puzzle: https://jsfiddle.net/timkelty/u766n8ah/2/ It appears the menu widget operates on `hierarchicalFacets`/`hierarchicalFacetsRefinements`, not `facets` or `disjunctiveFacets`.

This is still the case.
