### ISSUE TITLE
What is the url request to reset react instantsearch hits?

### ISSUE THREAD

**Issue by jackmatrix** [algolia/instantsearch.js#3041] opened 2018-07-22 22:25 UTC
I am using react instantsearch and sometime i need to check if my index has new entries without to be required to remounting my component.

So i know that when my component is called the first time, `react-instantsearch` make an initial request to fetch the most pertinent hits :

```javascript
 export const Hits = connectInfiniteHits(({ hits, hasMore, refine,currentRefinement}) => {




return (


  <View>//put my Hits here//</View>

);
});
```

So in my case i need to re-fetch hits sometimes but when i call a new instance of `<Hits />`  i get the same result even if my index has new entries. I always need to manually reset my component to see the changes.

I may have need a simple url to fetch and update my hits, for ex : `axios.get('/getLastHits'....`

Any idea ?

**Comment by Haroenv** [comment] 2018-07-22 22:55
Duplicate of https://github.com/algolia/algoliasearch-client-javascript/issues/715#issuecomment-406903374 and https://github.com/algolia/react-instantsearch/issues/1454#event-1746606561, let’s keep the discussion in the React InstantSearch issue if any more is necessary :)

**Closed by Haroenv** 2018-07-22 22:55 UTC
