### ISSUE TITLE
[rangeslider] Let the user configure set the min and max values.

### ISSUE THREAD

**Issue by bobylito** [algolia/instantsearch.js#870] opened 2016-02-24 15:47 UTC
There is an issue in Algolia engine that makes the empty query return wrong min and max values. One quick fix is to let the user configure a fixed min and max values.

What do you think?

**Comment by vvo** [comment] 2016-02-24 17:15
Yes we should do it.

I think its a duplicate of https://github.com/algolia/instantsearch.js/issues/858. If that's the case you lost 20 points in the contributor game. :D

**Closed** 2016-02-24 18:03 UTC
Labels: duplicate

**Comment by bobylito** [comment] 2016-02-25 13:12
Oh no!! #fail
