### ISSUE TITLE
Configuring hitsPerPage in initialization has no effect

### ISSUE THREAD

**Issue by mfbx9da4** [algolia/instantsearch.js#2752] opened 2018-02-27 00:42 UTC
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**
```
    var search = instantsearch({
      // Replace with your own values
      appId: '8AOQAW9EZA',
      apiKey: '8caaee2531c0957918fc460b01e2acbb', // search only API key, no ADMIN key
      indexName: 'sf-events',
      urlSync: true,
      searchParameters: {
        hitsPerPage: 500
      }
    });
``` 

has no effect
**Bug: What is the expected behavior?**
should be 500 items in page
**Bug: What browsers are impacted? Which versions?**
all
**Bug: What is the proposed solution?**
update docs
**Feature: What is your use case for such a feature?**

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

**What is the version you are using? Always use the latest one before opening a bug issue.**

**Comment by vvo** [comment] 2018-02-27 14:55
Can you check that you have no other hitsPerPage configured in another widget or in your url? Thanks

**Comment by bobylito** [comment] 2018-02-28 08:53
I can't reproduce with the latest version in this example: https://codesandbox.io/s/24vkwxoo30

**Comment by bobylito** [comment] 2018-03-12 15:27
I can't reproduce this issue so I'm gonna close it for now. Thanks for opening an issue here 👍 . Feel free to open a new one, if need be.

**Closed by bobylito** 2018-03-12 15:27 UTC
Labels: ❔ Investigate, ❤ Bug
