### ISSUE TITLE
Inconsistency between facet widgets for hasResults

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instantsearch.js#394] opened 2015-10-30 15:01 UTC
We sometimes use `facetValues.length`, some others `nbHits` (or even `hits.length`, leading to even more inconsistency).
I think we should:
- either rename `hideContainerWhenNoResults` to `hideContainerWhenNoRefinements` for them and use `facetValues`
- or expose both, with `hideContainerWhenNoRefinements = false` and `hideContainerWhenNoResults = true`

WDYT?

**Comment by pixelastic** [comment] 2015-11-02 09:17
@Jerskouille Is this still accurate with the refactoring on the `autoHide` decorator?

**Comment by Jerskouille** [comment] 2015-11-02 09:58
Yes, that's how I saw it, but I didn't fix it.

**Comment by vvo** [comment] 2015-11-02 14:16
I think most of the time what you want is "hideContainerWhenNoResults". Because if there's no results then there's no facets?

So maybe we should always use nbHits internally for consistency if it's ok with you.

**Comment by vvo** [comment] 2015-11-02 14:16
(removed the bug label, this is not a bug right now)

**Comment by Jerskouille** [comment] 2015-11-02 14:22
The behaviour can be really different as soon as we have `null` on some facet values. Some blocks might be displayed when there is actually nothing in it.
And it is actually a bug since some are using `nbHits` (`price-ranges`, `toggle`), and others are using `facetValues.length` (`refinement-list`, `menu`, `hierarchical-menu`), meaning that they don't behave consistently when there are `null` values.

**Comment by Jerskouille** [comment] 2015-11-02 14:23
And with `hitsPerPage: 0`, it's also inconsistent, hence the `bug` tag.

**Comment by vvo** [comment] 2015-11-02 14:28
Ok better understood the bug (facet values containing null) => leads to a bug.

`hideContainerWhenNoResults` still seems ok as for naming and having only one option. Maybe we just need to ensure to only check the relevant information to hide/display the widget (which is the number of available refinements in the end).

**Comment by vvo** [comment] 2015-11-02 14:29
So the actual bug is that in some widget we keep rendering them even when the refinement array is empty right?

**Comment by Jerskouille** [comment] 2015-11-02 14:36
I actually don't know. Maybe it's what we want.
It's more that the parameter name is inconsistent with the behaviour.

**Comment by Jerskouille** [comment] 2015-11-02 14:44
By the way, I'm already introducing `hideContainerWhenNoRefinents` in #404 and #405 .

**Comment by vvo** [comment] 2015-11-02 14:55
Ah indeed hideContainerWhenNoRefinements would then have two meanings. Maybe we should just have "autoHide: true/false" like we had at the begining then handle the implementation differently.

I am not sure the user need so much detail, it should just hide when it's obvious (either no results or no refinements).

**Comment by Jerskouille** [comment] 2015-11-02 15:00
I'm ok with an `autoHideContainer`.

**Comment by vvo** [comment] 2015-11-02 15:08
> I'm ok with an autoHideContainer.

:v: WFM nice

**Comment by vvo** [comment] 2015-11-02 15:09
closing in favor of #407

**Closed by vvo** 2015-11-02 15:09 UTC
Labels: question
