### ISSUE TITLE
Always show all categories, even if empty

### ISSUE THREAD

**Issue by MrMooky** [algolia/instantsearch.js#2329] opened 2017-09-12 12:30 UTC
My current setup looks somewhat like this:

```js
var search = instantsearch({
        appId: appId,
        apiKey: apiKey,
        indexName: 'kategorien',
        urlSync: false,
        searchParameters: {
                hierarchicalFacetsRefinements: {
                        facet: ['Fehlbildungen']
                }
        }
});

search.addWidget(
        instantsearch.widgets.searchBox({
                container: '#indikationen_search'
        })
);

search.addWidget(
        instantsearch.widgets.menu({
                container: '#categories',
                attributeName: 'facet',
                sortBy: ['name:asc']
        })
);

search.start();

// reset set filters when typing
$('input#indikationen_search').on('keyup', function(){
        search.helper.clearRefinements();
});
```

By default Algolia hides all categories/facet that have no result when I type something, so the categories expand to full width, which looks odd:

![screen shot 2017-09-12 at 2 27 18 pm](https://user-images.githubusercontent.com/3603346/30325840-95b9d0c0-97c6-11e7-9f8a-369cc7627b9d.png)

Standard:

![screen shot 2017-09-12 at 2 27 10 pm](https://user-images.githubusercontent.com/3603346/30325850-a688f296-97c6-11e7-8c45-02a694cde858.png)

**Is it possible to have all categories visible but to disable them (when there are no results within a facet/category), so a user cannot click on them? But they should be visible at all times.**

**Comment by Haroenv** [comment] 2017-09-12 12:58
Thanks for your feedback, however this is an engine limitation. You have two options here: 

1. statically say which items the menu has
2. make the answer return the facet, even if it has 0 results

The second option would be the preferable for you, but it's not possible. I did put it on our internal feedback board. 

duplicate of https://github.com/algolia/algoliasearch-client-javascript/issues/541

**Comment by bobylito** [comment] 2017-09-12 13:34
To complete @Haroenv's answer, the second option can be emulated using a first empty query. In order to do this you need to [create a custom widget](https://community.algolia.com/instantsearch.js/v2/guides/custom-widget.html).

During the init, you should use the helper to make a new query using [searchOnce](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#searchOnce) and with the answer build your menu items. The facet values that you retrieve then can be used for filtering, with [helper.toggleFacetRefinement](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#toggleFacetRefinement).

The idea is that since you want a static menu, you shouldn't need to rerender anything afterwards.

**Closed by bobylito** 2017-09-12 13:34 UTC
Labels: Difficulty:  ❄️❄️ medium, Doc: guide, Scope: widgets, ❔ Question
